### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by vaibhavpacharya** [CodeSprut/GiftSeeker#17]
Getting below error on running npm start

```
TypeError: Cannot read property '0' of null
    at Object.<anonymous> (/Users/vaibhavacharya/Desktop/Web Development/GiftSeeker/src/environment.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/vaibhavacharya/Desktop/Web Development/GiftSeeker/src/electron/app.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

<img width="1228" alt="Screen Shot 2021-11-23 at 11 14 11 AM" src="https://user-images.githubusercontent.com/16417441/143061990-ad29909a-125a-4465-a69f-65b1c9506838.png">

**Comment by codesprut** [comment]
Hello!
Which OS are you using?

**Comment by codesprut** [comment]
Not windows. I think)
Thanks for your feedback

**Comment by vaibhavpacharya** [comment]
> 

Mac Catalina.
